### ISSUE TITLE
US1 User account creation

### ISSUE THREAD

**Issue by sofiamancini** [cquinn417/Greenway#26]

**Comment by JunL23** [comment]
AS A user,
I WANT TO create an account using email/password authentication,
TO store and manage my to-do list items on the Internet
SO THAT I can access and manage my tasks from the app across different devices.

SCENARIO: Successful Account Creation
GIVEN the user is on the sign-up screen of the GreenWay app,
WHEN the user enters a valid email address and a strong password,
AND clicks the "Create Account" button,
THEN an account should be created in the Firebase authentication system,
WITHIN 3 seconds,
AND the user should be redirected to the main app screen,
WITHIN 2 seconds.

SCENARIO: Account Already Exists
GIVEN the user is on the sign-up screen of the GreenWay app,
WHEN the user enters an email address that is already associated with an existing account,
AND clicks the "Create Account" button,
THEN the system should display an error message stating "An account with this email already exists"
WITHIN 1 second,
AND prompt the user to either log in or recover their password.

SCENARIO: Invalid Email Address Format
GIVEN the user is on the sign-up screen of the GreenWay app
WHEN the user enters an email address that does not follow a valid email format (e.g., "userexample.com" or "[user@.com](mailto:user@.com)"),
AND clicks the "Create Account" button,
THEN the system should display an error message stating "Please enter a valid email address"
WITHIN 1 second,
AND prevent the account creation process from proceeding.
