### ISSUE TITLE
US3 Backend setup

### ISSUE THREAD

**Issue by sofiamancini** [cquinn417/Greenway#28]

**Comment by cquinn417** [comment]
User Story: Backend Setup
AS A user, 
I WANT TO track my sustainability habits 
[INSTEAD OF using manual tracking or scattered apps] 
IN real-time 
TO monitor and improve my eco-friendly practices 
SO THAT I can reduce my carbon footprint and contribute to a more sustainable lifestyle.

SCENARIO: User tracks sustainability habits automatically
GIVEN the user has logged into the app,
WHEN they perform activities such as using public transport, composting, or reducing energy consumption,
AND input these actions into the app or have the app automatically detect them,
THEN the app updates the user’s sustainability progress dashboard WITHIN 5 seconds of the activity being logged,
AND generates a weekly report of their environmental impact improvement WITHIN 7 days.

SCENARIO: Backend setup failure affects tracking
GIVEN the app’s backend setup (including Firestore database and 305Soft NoSQL Database Schema) has failed during initialization,
WHEN the user attempts to log or track their sustainability activities,
AND the system is unable to retrieve or store the data,
THEN the app displays a user-friendly error message WITHIN 1 second of detecting the issue,
AND prompts the user to try again or contact support WITHIN 5 seconds.
