### ISSUE TITLE
US4 [Golden Path]

### ISSUE THREAD

**Issue by sofiamancini** [cquinn417/Greenway#29]

**Comment by carz0987** [comment]
As a user who is conscious about my environmental impact,
I want to view my tracking stats and add new activities directly from the home screen,
So that I can monitor and improve my eco-friendly habits effortlessly.

Given the user has already installed the Eco-Tracker app and has existing tracking data,
When the user opens the app,
Then the home screen should immediately display their current eco-friendly activities (e.g., carbon footprint, recycling stats, water conservation, etc.) in an easy-to-read format (such as a graph or card).

And there is a clear “+” button or “New Entry” button on the screen,
When the user taps the “+” button,
Then the app navigates to the "New Activity" screen, where the user can select from pre-defined eco-friendly actions (e.g., cycling instead of driving, using reusable bags, reducing electricity usage).
When the user submits the new activity,
Then the new data is instantly added to their tracking stats, and they are redirected to the home screen to view the updated stats.
